name: Update main Database Schema

on:
  workflow_call:
    inputs:
      run_migration:
        description: 'Run migration?'
        required: true
        type: boolean
    branches:
      - postgresSQL

jobs:
  approve_and_migrate:
    name: Approve and Migrate DB changes to Production
    runs-on: ubuntu-latest

    environment:
      name: Production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: npm install
      
      - name: Check for migration changes
        id: migration_check
        run: |
          git fetch --depth=2
          if git diff --quiet HEAD~1 HEAD --migrations; then
            echo "No changes in migration folder."
            echo " changed=false" >> $GITHUB_OUTPUT
          else 
            echo "Migration files have changes."
            echo " changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Run Migrations
        if: ${{ inputs.run_migration && steps.migration_check.changed == 'true' }}
        run: npm run migrate:up
        env:
          DATABASE_URL: "${{ secrets.DATABASE_URL }}"